FROM ubuntu:18.04
MAINTAINER showwin <ito@scouty.co.jp>

ENV LANG en_US.UTF-8

RUN apt-get update --fix-missing
RUN apt-get install -y wget sudo less vim git

# scouty ユーザ作成
RUN groupadd -g 1001 scouty && \
    useradd  -g scouty -G sudo -m -s /bin/bash scouty && \
    echo 'scouty:scouty' | chpasswd
RUN echo 'scouty ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# MySQL のインストール
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-server mysql-server/root_password password scouty'"]
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-service mysql-server/mysql-apt-config string 4'"]
RUN apt-get install -y mysql-server

# Nginx のインストール
RUN apt-get install -y nginx
COPY admin/config/nginx.conf /etc/nginx/nginx.conf

USER scouty

# Ruby のインストール
RUN sudo apt-get install -y ruby-dev libssl-dev libreadline-dev gcc make libmysqlclient-dev && \
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
RUN PATH="$HOME/.rbenv/bin:$PATH" && \
    eval "$(rbenv init -)" && \
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build && \
    rbenv install 2.5.1 && rbenv rehash && rbenv global 2.5.1

# Python のインストール
RUN sudo apt-get install -y curl
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    PYENV_ROOT="$HOME/.pyenv" && PATH="$PYENV_ROOT/bin:$PATH" && \
    eval "$(pyenv init --path)" && \
    pyenv install 3.6.5 && pyenv global 3.6.5 && \
    cd && curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py && python get-pip.py && rm get-pip.py

# Go のインストール
RUN sudo wget https://dl.google.com/go/go1.14.7.linux-amd64.tar.gz && \
    sudo tar -C /usr/local -xzf go1.14.7.linux-amd64.tar.gz && \
    sudo rm go1.14.7.linux-amd64.tar.gz
ENV PATH $PATH:/usr/local/go/bin
ENV GOROOT /usr/local/go
ENV GOPATH $HOME/.local/go
ENV PATH $PATH:$GOROOT/bin

# アプリケーション
RUN mkdir /home/scouty/data /home/scouty/webapp
COPY --chown=scouty:scouty webapp/ /home/scouty/webapp
COPY --chown=scouty:scouty benchmark.py /home/scouty/benchmark.py
COPY --chown=scouty:scouty admin/config/bashrc /home/scouty/.bashrc

# ライブラリのインストール
RUN cd /home/scouty/webapp/ruby && sudo gem update --system && sudo gem install bundler -v "2.1.4" && bundle install
RUN LC_ALL=C.UTF-8 && LANG=C.UTF-8 && cd /home/scouty/webapp/python && \
    /home/scouty/.pyenv/shims/pip install -r requirements.txt

COPY --chown=scouty:scouty docker/start_app.sh /docker/start_app.sh
RUN chmod 700 /docker/start_app.sh

WORKDIR /home/scouty
EXPOSE 80
