source "https://rubygems.org"

gem 'rake'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'authlogic'
gem 'activesupport'
gem 'faraday'
gem 'puma'
gem 'scrypt'

group :development do
  gem 'sinatra-contrib'
  gem 'pry-byebug'
end

group :test do
  gem 'rspec'
  gem 'minitest'
  gem 'rack-test'
  gem 'rack-minitest'
  gem 'test-unit'
  gem 'database_cleaner'
end
