on:
  workflow_dispatch:
  pull_request:

name: Check refactor_code

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  refactor_code:
    name: Check refactor_code
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        language:
          - "python"
          - "ruby"
    steps:
      - uses: actions/checkout@v2

      - run: docker-compose build
        working-directory: refactor_code/${{ matrix.language }}

      - run: ../../scripts/start_docker_compose.bash "app_1" "start application"
        working-directory: refactor_code/${{ matrix.language }}

      - run: docker exec -t ${{ matrix.language }}_app_1 /app/docker/service/run_test.sh
        working-directory: refactor_code/${{ matrix.language }}
